#include <string>

using namespace std;

string systematics[14] = { "_JER_do","_JER_up",
                               "_JES_do","_JES_up",
                               "_gluonSplitting_do","_gluonSplitting_up",
                               "_bFragmentation_do","_bFragmentation_up",
                               "_cFragmentation_do","_cFragmentation_up",
                               "_cdFragmentation_do","_cdFragmentation_up",
                               "_v0_do","_v0_up",


void doMove(TFile* filein, TFile* fileout, TString dirout, bool normalize) {
   // example of script to loop on all the objects of a ROOT file directory
   // and print on Postscript all TH1 derived objects
   // This script uses the file generated by tutorial hsimple.C
   //Author: Rene Brun
   TDirectory* dir = fileout->mkdir(dirout); 
   TIter next(filein->GetListOfKeys());
   TKey *key;
   TCanvas c1;
   while ((key = (TKey*)next())) {
      TClass *cl = gROOT->GetClass(key->GetClassName());
      if (!cl->InheritsFrom("TH1")) continue;
      TH1 *h = (TH1*)key->ReadObj();
      if (normalize){
        cout << h->GetName() << endl;
        
        h->Scale(1./h->Integral());
      }  
      dir->cd();
      h->Write();
   }
}

void merge(TString filenamein, TString filenameout, TString dir, bool normalize){
  TFile* fileout = new TFile(filenameout, "update");
  TFile* filein = new TFile(filenamein);

  doMove(filein, fileout, dir, normalize);

  filein->Close();  
  fileout->Close();
  delete fileout;
  delete filein;
}
